<!doctype html>
<html>
<head>
<meta charset="UTF-8">
<meta content="width=device-width, initial-scale=1.0, maximum-scale=1" name="viewport" />
<title>Platyphant</title>
<link rel="shortcut icon" href="assets/images/favicon.png"/>
<link rel="stylesheet" href="style.css">
<link href="https://fonts.googleapis.com/css?family=Bitter:400|Lato:100,300,400,400i,700" rel="stylesheet">

</head>

<body>

	<nav>

	</nav>

	<section>

	</section>

	<h1>Lorem ipsum dolor</h1>
	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras consequat turpis laoreet aliquam volutpat. Aenean dui elit, venenatis eget accumsan a, lacinia et enim. <a href="http://vcburnett.com">Mauris sodales mi vel</a> accumsan aliquam. Donec ultricies blandit tellus, at iaculis est porttitor nec. Integer condimentum sapien id leo iaculis, eu convallis arcu blandit. Integer volutpat auctor finibus. Integer non sollicitudin erat. Integer id nisl ut odio vulputate tincidunt sed vitae libero. Quisque quis orci eget massa dapibus euismod. Sed in ex at lectus mollis vestibulum vel non nulla. Integer at orci et risus fermentum vehicula consequat eget velit.</p>
	<p>Quisque laoreet ultrices diam eu ornare. Etiam risus magna, pretium non interdum vel, vehicula eget urna. Proin fringilla molestie pulvinar. Etiam eu placerat mi, vel finibus nunc. Nam mollis, tellus vitae malesuada blandit, leo dolor congue risus, luctus ultrices libero tellus vitae neque. Pellentesque lacinia malesuada dolor ac fringilla. Ut congue felis sit amet urna placerat fringilla. Nullam facilisis lobortis est, at condimentum felis consectetur a. Suspendisse et orci in odio viverra eleifend id quis nunc.</p>
	<h3>This is a h3</h3>
	<h2>Nullam facilisis lobortis est, at condimentum felis consectetur a.</h2>
	<p>Etiam eget aliquam est, at lobortis quam. Quisque rutrum facilisis metus, ut congue tortor pellentesque sit amet. Mauris quis velit dolor. Proin varius pulvinar nibh. Maecenas a ante lacinia, sodales leo ut, viverra nulla. Nam a nisi vitae risus scelerisque molestie. Donec dignissim quam quis risus dictum, sit amet tempor erat posuere.</p>
	<p>Integer gravida lectus ac neque iaculis pharetra. Integer velit ipsum, finibus et molestie id, iaculis et risus. Vivamus tristique quam eros, eu varius libero dapibus sed. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Curabitur a risus venenatis, volutpat odio vel, egestas felis. Duis sollicitudin scelerisque felis vitae accumsan. Nam sed nulla sed libero imperdiet semper non at velit. Morbi sed lobortis ante. Praesent consectetur feugiat eros, imperdiet malesuada mi pretium eget. Sed pharetra metus at turpis pellentesque, nec placerat tellus convallis. Praesent posuere eget dui eget egestas. Sed eu velit elit. Aliquam vel purus quis mi blandit commodo dignissim eget dui. Quisque libero nulla, tincidunt ut quam ut, pretium eleifend dolor. Quisque sit amet semper metus.</p>
	<p>Fusce vitae enim consectetur, lacinia sapien ut, congue leo. Donec orci dolor, consequat quis ex faucibus, sodales ultricies mi. Maecenas porta ornare ipsum a pharetra. Fusce ultrices eros vitae venenatis consectetur. Curabitur dictum est sit amet nisl ultrices commodo. Aenean gravida est urna, sit amet malesuada quam gravida nec. Proin id lectus congue, sagittis lectus ut, euismod neque. Proin mi magna, pharetra sed congue ac, venenatis nec ex. Aenean vestibulum, nunc vitae dapibus bibendum, massa risus tincidunt ante, sed finibus metus urna a augue. Vivamus tempus diam nisi, sit amet faucibus ex maximus nec. Nam molestie pretium accumsan. Etiam nec metus ex. Vivamus viverra mi sapien, a porta leo hendrerit eget. Nam consequat fermentum magna in molestie.</p>
	<a class="more-info" href="http://google.com">More info <span class="link-arrow"><svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 198 126.7" xml:space="preserve" style="enable-background:new 0 0 198 126.7;"><path d="M195.1,70.4l-53.4,53.4c-1.9,1.9-4.5,2.9-7.1,2.9s-5.1-1-7.1-2.9c-3.9-3.9-3.9-10.2,0-14.1L164,73.3H10c-5.5,0-10-4.5-10-10s4.5-10,10-10h154L127.6,17c-3.9-3.9-3.9-10.2,0-14.1c3.9-3.9,10.2-3.9,14.1,0l53.4,53.4C199,60.2,199,66.5,195.1,70.4z"/></svg></span></a>
	<p>Integer gravida lectus ac neque iaculis pharetra. Integer velit ipsum, finibus et molestie id, iaculis et risus. Vivamus tristique quam eros, eu varius libero dapibus sed. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Curabitur a risus venenatis, volutpat odio vel, egestas felis. Duis sollicitudin scelerisque felis vitae accumsan. Nam sed nulla sed libero imperdiet semper non at velit. Morbi sed lobortis ante. Praesent consectetur feugiat eros, imperdiet malesuada mi pretium eget. Sed pharetra metus at turpis pellentesque, nec placerat tellus convallis. Praesent posuere eget dui eget egestas. Sed eu velit elit. Aliquam vel purus quis mi blandit commodo dignissim eget dui. Quisque libero nulla, tincidunt ut quam ut, pretium eleifend dolor. Quisque sit amet semper metus.</p>
	<p>Fusce vitae enim consectetur, lacinia sapien ut, congue leo. Donec orci dolor, consequat quis ex faucibus, sodales ultricies mi. Maecenas porta ornare ipsum a pharetra. Fusce ultrices eros vitae venenatis consectetur. Curabitur dictum est sit amet nisl ultrices commodo. Aenean gravida est urna, sit amet malesuada quam gravida nec. Proin id lectus congue, sagittis lectus ut, euismod neque. Proin mi magna, pharetra sed congue ac, venenatis nec ex. Aenean vestibulum, nunc vitae dapibus bibendum, massa risus tincidunt ante, sed finibus metus urna a augue. Vivamus tempus diam nisi, sit amet faucibus ex maximus nec. Nam molestie pretium accumsan. Etiam nec metus ex. Vivamus viverra mi sapien, a porta leo hendrerit eget. Nam consequat fermentum magna in molestie.</p>
	<a class="cta-1" href="http://google.com/">This is CTA 1</a>
	<p>Integer gravida lectus ac neque iaculis pharetra. Integer velit ipsum, finibus et molestie id, iaculis et risus. Vivamus tristique quam eros, eu varius libero dapibus sed. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Curabitur a risus venenatis, volutpat odio vel, egestas felis. Duis sollicitudin scelerisque felis vitae accumsan. Nam sed nulla sed libero imperdiet semper non at velit. Morbi sed lobortis ante. Praesent consectetur feugiat eros, imperdiet malesuada mi pretium eget. Sed pharetra metus at turpis pellentesque, nec placerat tellus convallis. Praesent posuere eget dui eget egestas. Sed eu velit elit. Aliquam vel purus quis mi blandit commodo dignissim eget dui. Quisque libero nulla, tincidunt ut quam ut, pretium eleifend dolor. Quisque sit amet semper metus.</p>
	<p>Fusce vitae enim consectetur, lacinia sapien ut, congue leo. Donec orci dolor, consequat quis ex faucibus, sodales ultricies mi. Maecenas porta ornare ipsum a pharetra. Fusce ultrices eros vitae venenatis consectetur. Curabitur dictum est sit amet nisl ultrices commodo. Aenean gravida est urna, sit amet malesuada quam gravida nec. Proin id lectus congue, sagittis lectus ut, euismod neque. Proin mi magna, pharetra sed congue ac, venenatis nec ex. Aenean vestibulum, nunc vitae dapibus bibendum, massa risus tincidunt ante, sed finibus metus urna a augue. Vivamus tempus diam nisi, sit amet faucibus ex maximus nec. Nam molestie pretium accumsan. Etiam nec metus ex. Vivamus viverra mi sapien, a porta leo hendrerit eget. Nam consequat fermentum magna in molestie.</p>
	<a class="cta-2" href="http://google.com/">Thi sis CTA 2</a> <a class="cta-1" href="http://google.com/">Now CTA 1</a>
	<p>Integer gravida lectus ac neque iaculis pharetra. Integer velit ipsum, finibus et molestie id, iaculis et risus. Vivamus tristique quam eros, eu varius libero dapibus sed. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Curabitur a risus venenatis, volutpat odio vel, egestas felis. Duis sollicitudin scelerisque felis vitae accumsan. Nam sed nulla sed libero imperdiet semper non at velit. Morbi sed lobortis ante. Praesent consectetur feugiat eros, imperdiet malesuada mi pretium eget. Sed pharetra metus at turpis pellentesque, nec placerat tellus convallis. Praesent posuere eget dui eget egestas. Sed eu velit elit. Aliquam vel purus quis mi blandit commodo dignissim eget dui. Quisque libero nulla, tincidunt ut quam ut, pretium eleifend dolor. Quisque sit amet semper metus.</p>
	<p>Fusce vitae enim consectetur, lacinia sapien ut, congue leo. Donec orci dolor, consequat quis ex faucibus, sodales ultricies mi. Maecenas porta ornare ipsum a pharetra. Fusce ultrices eros vitae venenatis consectetur. Curabitur dictum est sit amet nisl ultrices commodo. Aenean gravida est urna, sit amet malesuada quam gravida nec. Proin id lectus congue, sagittis lectus ut, euismod neque. Proin mi magna, pharetra sed congue ac, venenatis nec ex. Aenean vestibulum, nunc vitae dapibus bibendum, massa risus tincidunt ante, sed finibus metus urna a augue. Vivamus tempus diam nisi, sit amet faucibus ex maximus nec. Nam molestie pretium accumsan. Etiam nec metus ex. Vivamus viverra mi sapien, a porta leo hendrerit eget. Nam consequat fermentum magna in molestie.</p>

</body>
</html>